### ISSUE TITLE
Agregar meta etiquetas sociales

### ISSUE THREAD

**Issue by ricardoerl** [horchatajs/website#6]
- [x] Etiquetas para SEO
- [x] Etiquetas para Facebook
- [x] Etiquetas para Twitter

Más información: https://github.com/joshbuchea/HEAD#social
